### DISCUSSION TITLE
SC4SNMP NEXT (0.11.0-beta.35)

### DISCUSSION THREAD

**Discussion by ryanfaircloth** [splunk/splunk-connect-for-snmp#183] [General]
Documentation for Beta 3 is in the next branch but is slighly behind
https://splunk.github.io/splunk-connect-for-snmp/next/
example values.conf

#Command Note the version should be the latest next from the release page
https://github.com/splunk/splunk-connect-for-snmp/releases

## Install/Upgrade
``` bash
microk8s helm3 repo update
microk8s helm3 upgrade --install snmp -f values.yaml splunk-connect-for-snmp/splunk-connect-for-snmp \
--namespace=sc4snmp --create-namespace --version 0.11.0-beta.35
```

#Note please see develop docs /configuration for instructions on snmpv3 setup
``` yaml
splunk:
  protocol: https
  host: splunk-s1-standalone-service.splunk.svc.cluster.local
  token: XXXXX
  insecureSSL: "true"
  port: "8088"
  clusterName: homecluster
image:
  image: ghcr.io/splunk/splunk-connect-for-snmp/container
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.11.0-beta.35"
traps:
  communities:
    2c:
      - public
      - homelab
#  usernameSecrets:
#    - sc4snmp-homesecure-sha-aes
  # Overrides the image tag whose default is the chart appVersion.
  #  logLevel: "WARN"
  # replicas: Number of replicas for trap container should be 2x number of nodes
  replicas: 2
  #loadBalancerIP: The IP address in the metallb pool
  loadBalancerIP: 10.1.0.1
poller:
#  usernameSecrets:
#    - sc4snmp-homesecure-sha-aes
#    - sc4snmp-homesecure-sha-des
  inventory: |
    address,version,community,walk_interval,profiles,SmartProfiles,delete
    10.0.0.199,3,sc4snmp-homesecure-sha-des,600,,,
    10.0.0.1,3,sc4snmp-homesecure-sha-aes,600,,,
    10.0.0.195,2c,homelab,600,,,  
worker:
  replicas: 2
  logLevel: "DEBUG"
scheduler:
  logLevel: "DEBUG"
#Note storageClasses below are correct for single instance. When "clustered" another storage class such as openebs-jiva is appropriate
mongodb:
  persistence:
    storageClass: "microk8s-hostpath"
  volumePermissions:
    enabled: true
rabbitmq:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "microk8s-hostpath"
  volumePermissions:
    enabled: true

```
