### DISCUSSION TITLE
only last usernameSecrets in list in config.yaml is taken

### DISCUSSION THREAD

**Discussion by frankli-n** [splunk/splunk-connect-for-snmp#967] [Q&A]
It seems there is an issue when adding multiple usernameSecrets that only the last one in the list is taken.
 
```
splunk:
  enabled: true
  protocol: http
  host: 192.168.157.134
  token: 9754a1da-***-cb41b1780726
  insecureSSL: "true"
  port: "8088"
traps:
  communities:
    2c:
      - public
      - homelab
  loadBalancerIP: 192.168.157.10
  usernameSecrets:
    - snmpv3-secret-md5-aes128
    - snmpv3-secret-sha-aes
    - snmpv3-secret-md5-des
    - snmpv3-secret-md5-aes
  securityEngineId:
    - "80003a8c04" # Testing
    - "80003a8c05" # Testing
    - "80003a8c06" # Testing
    - "80003a8c07" # Testing
  logLevel: "DEBUG"
```
