### ISSUE TITLE
Redis container limits configuration appear to have no effect

### ISSUE THREAD

**Issue by lukemonahantnt** [splunk/splunk-connect-for-snmp#1114]
I started experiencing an out-of-memory error, causing the splunk-connect-for-snmp-redis-master-0 to enter a crash loop. It was killed again by the OOM killer every time.

I increased the limits for this pod in values.yaml, as per: https://splunk.github.io/splunk-connect-for-snmp/main/configuration/deployment-configuration/#shared-values

```
redis:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
```

However there is no effect on the running pod:

```
# kubectl describe pod splunk-connect-for-snmp-redis-master-0 -n splunk-snmp

<snip>

    Limits:
      cpu:                150m
      ephemeral-storage:  2Gi
      memory:             192Mi
    Requests:
      cpu:                100m
      ephemeral-storage:  50Mi
      memory:             128Mi

```

Patching the container after creation was not possible. The only way to solve my OOM crash was to uninstall, remove the redis PVC and PV, and then reinstall.
