### ISSUE TITLE
Delay in profiles configuration acknowledgement while modifying inventory and profiles config at the same time

### ISSUE THREAD

**Issue by omrozowicz-splunk** [splunk/splunk-connect-for-snmp#431]
If we modify values.yaml inserting a new profile (let’s say new_profile) and at the same time add it to the static profiles in the inventory.csv (10.202.20.109,,2c,public,,,600,new_profile,,) then configMap that contains profiles reloads immediately, but not the corresponding file inside pod. The config is as follows:
```
volumes:
 # You set volumes at the Pod level, then mount them into containers inside that Pod
 - name: config
  configMap:
   # Provide the name of the ConfigMap you want to mount.
   name: {{ include "splunk-connect-for-snmp.name" . }}-config
   # An array of keys from the ConfigMap to create as files
   items:
    - key: "config.yaml"
     path: "config.yaml"
```
The problem appears because there is fixed ttl+cache time in kubernetes, and sometimes profile is correctly loaded after change in walk triggered by inventory job, sometimes not. When walk operation is long, it’s usually enough time for the file to be updated.
Everything works correctly when we first upgrade helm after bare profiles change, and then after inventory change.

Workaround:
1. Modify profiles part only
2. Upgrade helm
3. `microk8s kubectl delete jobs/snmp-splunk-connect-for-snmp-inventory -n sc4snmp`
4. Modify `inventory.csv` part
5. Upgrade helm
