### ISSUE TITLE
Issues loading local mibs

### ISSUE THREAD

**Issue by wsedgwick1** [splunk/splunk-connect-for-snmp#710]
Hi, having some issues getting local mibs to load. I think I'm following the docs correctly. Using a local user, kube-user, to run the containers with local mibs stored in their home directory.

Logs show the following message on restart:
`No local mibs. Skipping...`

containers are at the following versions (happy to run further commands to troubleshoot): 
ghcr.io/pysnmp/mibs/container:1.15.1
ghcr.io/splunk/splunk-connect-for-snmp/container:1.8.7-beta.2

values.yaml is as follows:
```
splunk:
  enabled: true
  protocol: https
  host: <URL>
  token: <TOKEN>
  insecureSSL: "true"
  port: "8088"
image:
  pullPolicy: "Always"
traps:
  communities:
    2c:
      - public
      - homelab
  loadBalancerIP: <IP>
worker:
  trap:
    replicaCount: 2
  poller:
    replicaCount: 2
  sender:
    replicaCount: 1
  logLevel: "INFO"
scheduler:
  logLevel: "INFO"
  profiles: |
    small_walk:
        frequency: 42000
        condition:
          type: "walk"
        varBinds:
          - ['SNMPv2-MIB']
    qnap_nas:
      frequency: 30
      varBinds:
        - ['NAS-MIB', 'systemTemperature']
        - ['QTS-MIB', 'diskCount']
poller:
  inventory: |
    address,port,version,community,secret,security_engine,walk_interval,profiles,smart_profiles,delete
    <VM IP>,,2c,public,,,42000,,,
    <NAS IP>,,2c,eEnXx8TnbYQxpjKF,,,42000,qnap_nas,,
sim:
  enabled: false
mongodb:
  pdb:
    create: true
  persistence:
    storageClass: "microk8s-hostpath"
  volumePermissions:
    enabled: true
mibserver:
  image:
    tag: "1.15.1"
  localMibs:
    pathToMibs: "/home_local/kube-user/local_mibs"
```

Any assistance in how to further troubleshoot/resolve the issue would be greatly appreciated as the SNMP data I have managed to get into Splunk has been really useful, but I would love to use proprietary MIBs as well.
