### ISSUE TITLE
Helm Installation Proxy Configuration and SOCKS5 Proxy Support Enhancement

### ISSUE THREAD

**Issue by symmr** [splunk/splunk-connect-for-snmp#737]
This request contains two aspects.

**1. Configuring Proxy during installation with helm**
**1.1. Adding configuration items in values.yaml**
For example, please make it possible to set the Proxy as follows:

```yaml
sender.proxy.enabled: true
sender.proxy.http: http://proxyserver_host_or_address:8080
sender.proxy.https: http://proxyserver_host_or_address:8080
```

**1.2. Updating the Sender Deployment Chart**
Please reflect the http and https proxy information specified in 1.1 in the deployment under `spec.template.spec.containers.env`.

```yaml: 
- name: http_proxy
  value: {sender.proxy.http}
- name: https_proxy
  value: {sender.proxy.https}
- name: no_proxy
  value: "snmp-mibserver"
```

Here, no_proxy is set as a fixed value.
As for the communication from Sender, what I found is addressed to "http://snmp-mibserver/index.csv", but if there are other hosts that may be sent, please add them.

**2. Please also enable SOCKS5 proxy**
Users using Splunk may adopt a SOCKS5 proxy instead of HTTP.
However `requests` module currently used in SC4SNMP does not support SOCKS5.
When I actually tried it, I got an error saying "requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support."

This should be resolved by adding the `requests[socks]` module to the dependencies.

https://requests.readthedocs.io/en/latest/user/advanced/#socks
